name: Lingvo
main: com.github.coegho.lingvo.Lingvo
version: 0.2
description: Multilanguage API for plugins
author: coegho

commands:
  lingvo:
    description: Change the current language for the user.
    usage: /lingvo <lang>
    aliases: [ling, lang]
    permission: lingvo.command
    
permissions:
  lingvo.*:
    description: All Lingvo commands and permissions.
    children:
      lingvo.command: true
    default: op 
  lingvo.command:
    description: Allows the use of /lingvo <lang> to change the language.
    default: true
